name: GitHub Actions Demo
on: 
  push:
    branches: [main]
    paths-ignore: [.github/**]
  pull_request:
    branches: [main]
  schedule:
    - cron: '15 6 * * 0'
  workflow_dispatch:
    
jobs:
  Build:
    runs-on: ubuntu-22.04
    steps:
      - name: Display the triggered event
        shell: bash
        run: echo ${{ github.event_name }}
      - name: Branch name
        shell: bash
        run: echo ${{ github.ref }}
      - uses: actions/checkout@v3.3.0
      - name: List files in the repository
        run: |
          echo "The repository ${{ github.repository }} contains the following files:"
          tree

